menu:
#- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'blog', url: '/blog'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

# people:
# - {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
# - {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
# - {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

# courses: could add things here, pdfs of posters or somthing? 
# - {name: 'Vector Calculus', url: 'vector-calculus'}
# - {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
# - {name: 'Stellar Structures', url: 'stellar-structures'}

blog:
- {name: 'Blog Post 1', url: '/blog/blog1/'} 

contact:
- {icon: 'github', link: 'https://github.com/bizmorgan'}
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
#- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/elizabeth-morgan-939151239'}

contacts: #change contact image to a picture of myself?
- {name: 'Elizabeth Morgan', title: 'PhD Student', department: 'Physics & Astronomy', institution: 'Cardiff University', email: 'morgane52@cardiff.ac.uk', image: 'assets/img/contact.jpg'}
